from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Dict


@dataclass
class Style:
    name: str
    css: str


@dataclass
class Framework:
    name: str
    html_template: str


BUILTIN_STYLES = [
    Style(
        name="clean-light",
        css="""
:root { --bg: #f7f8fa; --fg: #1f2937; --card: #ffffff; --accent: #2563eb; }
body { margin:0; font-family: Arial, sans-serif; background: var(--bg); color: var(--fg); }
main { max-width: 860px; margin: 32px auto; padding: 0 16px; }
article { background: var(--card); border-radius: 12px; padding: 28px; box-shadow: 0 8px 24px rgba(0,0,0,0.08); }
a { color: var(--accent); text-decoration: none; }
header, footer { opacity: 0.8; }
""".strip(),
    ),
    Style(
        name="dark-neon",
        css="""
:root { --bg: #0b0f1a; --fg: #d4e1ff; --card: #131a2b; --accent: #58f0ff; }
body { margin:0; font-family: "Segoe UI", sans-serif; background: radial-gradient(circle at top right,#1d2d56,var(--bg)); color: var(--fg); }
main { max-width: 860px; margin: 32px auto; padding: 0 16px; }
article { background: var(--card); border: 1px solid #2f3f70; border-radius: 14px; padding: 28px; box-shadow: 0 0 24px rgba(88,240,255,0.18); }
a { color: var(--accent); }
""".strip(),
    ),
    Style(
        name="paper-minimal",
        css="""
:root { --bg: #f5f2ea; --fg: #2b2620; --accent: #9c5d2e; }
body { margin:0; font-family: Georgia, serif; background: var(--bg); color: var(--fg); }
main { max-width: 780px; margin: 40px auto; padding: 0 16px; }
article { padding: 18px 6px; border-top: 3px double #8a7f70; border-bottom: 3px double #8a7f70; }
a { color: var(--accent); }
""".strip(),
    ),
]

BUILTIN_FRAMEWORKS = [
    Framework(
        name="classic",
        html_template="""
<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>{title}</title>
  <link rel="stylesheet" href="{style_href}" />
</head>
<body>
  <main>
    <header><h1>{blog_name}</h1><p>{subtitle}</p></header>
    <article>
      <h2>{title}</h2>
      <small>{date}</small>
      <div>{content_html}</div>
    </article>
    <footer><p>Generated by BlogAuto</p></footer>
  </main>
</body>
</html>
""".strip(),
    ),
    Framework(
        name="magazine",
        html_template="""
<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>{title}</title>
  <link rel="stylesheet" href="{style_href}" />
</head>
<body>
  <main>
    <header><h1>{blog_name}</h1></header>
    <article>
      <h2>{title}</h2>
      <p><em>{subtitle}</em></p>
      <div>{content_html}</div>
      <hr />
      <small>{date}</small>
    </article>
    <footer><a href="../index.html">返回主页</a></footer>
  </main>
</body>
</html>
""".strip(),
    ),
]


def write_builtins(styles_dir: Path, frameworks_dir: Path) -> None:
    styles_dir.mkdir(parents=True, exist_ok=True)
    frameworks_dir.mkdir(parents=True, exist_ok=True)

    for style in BUILTIN_STYLES:
        (styles_dir / f"{style.name}.css").write_text(style.css + "\n", encoding="utf-8")

    for framework in BUILTIN_FRAMEWORKS:
        (frameworks_dir / f"{framework.name}.html").write_text(
            framework.html_template + "\n", encoding="utf-8"
        )


def list_styles(styles_dir: Path) -> Dict[str, Path]:
    return {p.stem: p for p in sorted(styles_dir.glob("*.css"))}


def list_frameworks(frameworks_dir: Path) -> Dict[str, Path]:
    return {p.stem: p for p in sorted(frameworks_dir.glob("*.html"))}
